### ISSUE TITLE
This is poop

### ISSUE THREAD

**Issue by ColinEberhardt** [Charlotteis/poopthis#1]
Seriously, don't use this code, it stinks.

**Comment by Charlotteis** [comment]
Hi @ColinEberhardt, thanks for making an issue.

Unsure if this is a joke or not, so if you could clarify that would be great :)

**Comment by Charlotteis** [comment]
(I realise it probably is a joke, but these things can be ambiguous!)

**Comment by ColinEberhardt** [comment]
It was a joke :-p 

I love these silly modules!

**Comment by Charlotteis** [comment]
Oh, good! :dancer: 
I would like to do more but I am afraid I have peaked.
